version: 0.0.1
os: linux
files:
  - source: /
    destination: /opt/tomcat/johnson/webapps
hooks:
  BeforeInstall:
    - location: Scripts/copyWarToTomcat.sh
    timeout: 10
    runas: root
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 10
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 10
  ValidateService:
    - location: Scripts/MonitorService.sh
      timeout: 10
      runas: codedeployuser