version: 0.0
os: linux
files:
  - source: Content
    destination: /opt/tomcat/default/webapps
#permissions:
#  - object: /opt/tomcat/default/webapps/ROOT
#    pattern: "*"
#    owner: nobody
#    group: nobody
#    mode: 755
#    type:
#      - directory
#  - object: /opt/tomcat/default/webapps/ROOT
#    pattern: "*"
#    owner: nobody
#    group: nobody
#    mode: 644
#    type:
#      - file
hooks:
  ApplicationStop:
    - location: Scripts/EC2_Enter_Standby.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: Scripts/install_apache22_tomcat7_jdk7.sh
      timeout: 300
      runas: root
    - location: Scripts/StopApacheTomcat.sh
      timeout: 60
      runas: root
    - location: Scripts/EarseOldDeploy.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: Scripts/StartApacheTomcat.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: Scripts/VerifyTomcat.sh
      timeout: 300
      runas: root
    - location: Scripts/EC2_Exit_Standby.sh
      timeout: 60
      runas: root
